import shoe from "../assets/shoe.png";

const suggestedData = [
   {
      Category: "Boots",
      Products: [
         { id: 1, img: shoe, title: "Boots Model 1", price: 1000, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 2, img: shoe, title: "Boots Model 2", price: 1050, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 3, img: shoe, title: "Boots Model 3", price: 1100, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 4, img: shoe, title: "Boots Model 4", price: 1150, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 5, img: shoe, title: "Boots Model 5", price: 1200, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 6, img: shoe, title: "Boots Model 6", price: 1250, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 7, img: shoe, title: "Boots Model 7", price: 1300, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 8, img: shoe, title: "Boots Model 8", price: 1350, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 9, img: shoe, title: "Boots Model 9", price: 1400, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 10, img: shoe, title: "Boots Model 10", price: 1450, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 11, img: shoe, title: "Boots Model 11", price: 1500, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 12, img: shoe, title: "Boots Model 12", price: 1550, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 13, img: shoe, title: "Boots Model 13", price: 1600, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 14, img: shoe, title: "Boots Model 14", price: 1650, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 15, img: shoe, title: "Boots Model 15", price: 1700, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 16, img: shoe, title: "Boots Model 16", price: 1750, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 17, img: shoe, title: "Boots Model 17", price: 1800, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 18, img: shoe, title: "Boots Model 18", price: 1850, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 19, img: shoe, title: "Boots Model 19", price: 1900, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 20, img: shoe, title: "Boots Model 20", price: 1950, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 21, img: shoe, title: "Boots Model 21", price: 2000, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 22, img: shoe, title: "Boots Model 22", price: 2050, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 23, img: shoe, title: "Boots Model 23", price: 2100, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 24, img: shoe, title: "Boots Model 24", price: 2150, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 25, img: shoe, title: "Boots Model 25", price: 2200, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 26, img: shoe, title: "Boots Model 26", price: 2250, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 27, img: shoe, title: "Boots Model 27", price: 2300, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 28, img: shoe, title: "Boots Model 28", price: 2350, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 29, img: shoe, title: "Boots Model 29", price: 2400, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 30, img: shoe, title: "Boots Model 30", price: 2450, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 31, img: shoe, title: "Boots Model 31", price: 2500, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 32, img: shoe, title: "Boots Model 32", price: 2550, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 33, img: shoe, title: "Boots Model 33", price: 2600, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 34, img: shoe, title: "Boots Model 34", price: 2650, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 35, img: shoe, title: "Boots Model 35", price: 2700, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 36, img: shoe, title: "Boots Model 36", price: 2750, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 37, img: shoe, title: "Boots Model 37", price: 2800, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 38, img: shoe, title: "Boots Model 38", price: 2850, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 39, img: shoe, title: "Boots Model 39", price: 2900, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 40, img: shoe, title: "Boots Model 40", price: 2950, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 41, img: shoe, title: "Boots Model 41", price: 3000, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 42, img: shoe, title: "Boots Model 42", price: 3050, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 43, img: shoe, title: "Boots Model 43", price: 3100, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 44, img: shoe, title: "Boots Model 44", price: 3150, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 45, img: shoe, title: "Boots Model 45", price: 3200, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 46, img: shoe, title: "Boots Model 46", price: 3250, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 47, img: shoe, title: "Boots Model 47", price: 3300, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 48, img: shoe, title: "Boots Model 48", price: 3350, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 49, img: shoe, title: "Boots Model 49", price: 3400, description: "Durable and stylish boots perfect for casual and outdoor wear." },
         { id: 50, img: shoe, title: "Boots Model 50", price: 3450, description: "Durable and stylish boots perfect for casual and outdoor wear." }
      ]
   },

   {
      Category: "Sneakers",
      Products: [
         { id: 1, img: shoe, title: "Sneakers Model 1", price: 900, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 2, img: shoe, title: "Sneakers Model 2", price: 960, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 3, img: shoe, title: "Sneakers Model 3", price: 1020, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 4, img: shoe, title: "Sneakers Model 4", price: 1080, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 5, img: shoe, title: "Sneakers Model 5", price: 1140, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 6, img: shoe, title: "Sneakers Model 6", price: 1200, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 7, img: shoe, title: "Sneakers Model 7", price: 1260, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 8, img: shoe, title: "Sneakers Model 8", price: 1320, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 9, img: shoe, title: "Sneakers Model 9", price: 1380, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 10, img: shoe, title: "Sneakers Model 10", price: 1440, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 11, img: shoe, title: "Sneakers Model 11", price: 1500, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 12, img: shoe, title: "Sneakers Model 12", price: 1560, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 13, img: shoe, title: "Sneakers Model 13", price: 1620, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 14, img: shoe, title: "Sneakers Model 14", price: 1680, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 15, img: shoe, title: "Sneakers Model 15", price: 1740, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 16, img: shoe, title: "Sneakers Model 16", price: 1800, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 17, img: shoe, title: "Sneakers Model 17", price: 1860, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 18, img: shoe, title: "Sneakers Model 18", price: 1920, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 19, img: shoe, title: "Sneakers Model 19", price: 1980, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 20, img: shoe, title: "Sneakers Model 20", price: 2040, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 21, img: shoe, title: "Sneakers Model 21", price: 2100, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 22, img: shoe, title: "Sneakers Model 22", price: 2160, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 23, img: shoe, title: "Sneakers Model 23", price: 2220, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 24, img: shoe, title: "Sneakers Model 24", price: 2280, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 25, img: shoe, title: "Sneakers Model 25", price: 2340, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 26, img: shoe, title: "Sneakers Model 26", price: 2400, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 27, img: shoe, title: "Sneakers Model 27", price: 2460, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 28, img: shoe, title: "Sneakers Model 28", price: 2520, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 29, img: shoe, title: "Sneakers Model 29", price: 2580, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 30, img: shoe, title: "Sneakers Model 30", price: 2640, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 31, img: shoe, title: "Sneakers Model 31", price: 2700, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 32, img: shoe, title: "Sneakers Model 32", price: 2760, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 33, img: shoe, title: "Sneakers Model 33", price: 2820, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 34, img: shoe, title: "Sneakers Model 34", price: 2880, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 35, img: shoe, title: "Sneakers Model 35", price: 2940, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 36, img: shoe, title: "Sneakers Model 36", price: 3000, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 37, img: shoe, title: "Sneakers Model 37", price: 3060, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 38, img: shoe, title: "Sneakers Model 38", price: 3120, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 39, img: shoe, title: "Sneakers Model 39", price: 3180, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 40, img: shoe, title: "Sneakers Model 40", price: 3240, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 41, img: shoe, title: "Sneakers Model 41", price: 3300, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 42, img: shoe, title: "Sneakers Model 42", price: 3360, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 43, img: shoe, title: "Sneakers Model 43", price: 3420, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 44, img: shoe, title: "Sneakers Model 44", price: 3480, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 45, img: shoe, title: "Sneakers Model 45", price: 3540, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 46, img: shoe, title: "Sneakers Model 46", price: 3600, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 47, img: shoe, title: "Sneakers Model 47", price: 3660, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 48, img: shoe, title: "Sneakers Model 48", price: 3720, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 49, img: shoe, title: "Sneakers Model 49", price: 3780, description: "Comfortable and trendy sneakers for daily use and sports." },
         { id: 50, img: shoe, title: "Sneakers Model 50", price: 3840, description: "Comfortable and trendy sneakers for daily use and sports." }
      ]
   },

   {
      Category: "Loafers",
      Products: [
         { id: 1, img: shoe, title: "Loafers Model 1", price: 800, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 2, img: shoe, title: "Loafers Model 2", price: 850, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 3, img: shoe, title: "Loafers Model 3", price: 900, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 4, img: shoe, title: "Loafers Model 4", price: 950, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 5, img: shoe, title: "Loafers Model 5", price: 1000, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 6, img: shoe, title: "Loafers Model 6", price: 1050, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 7, img: shoe, title: "Loafers Model 7", price: 1100, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 8, img: shoe, title: "Loafers Model 8", price: 1150, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 9, img: shoe, title: "Loafers Model 9", price: 1200, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 10, img: shoe, title: "Loafers Model 10", price: 1250, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 11, img: shoe, title: "Loafers Model 11", price: 1300, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 12, img: shoe, title: "Loafers Model 12", price: 1350, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 13, img: shoe, title: "Loafers Model 13", price: 1400, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 14, img: shoe, title: "Loafers Model 14", price: 1450, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 15, img: shoe, title: "Loafers Model 15", price: 1500, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 16, img: shoe, title: "Loafers Model 16", price: 1550, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 17, img: shoe, title: "Loafers Model 17", price: 1600, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 18, img: shoe, title: "Loafers Model 18", price: 1650, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 19, img: shoe, title: "Loafers Model 19", price: 1700, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 20, img: shoe, title: "Loafers Model 20", price: 1750, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 21, img: shoe, title: "Loafers Model 21", price: 1800, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 22, img: shoe, title: "Loafers Model 22", price: 1850, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 23, img: shoe, title: "Loafers Model 23", price: 1900, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 24, img: shoe, title: "Loafers Model 24", price: 1950, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 25, img: shoe, title: "Loafers Model 25", price: 2000, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 26, img: shoe, title: "Loafers Model 26", price: 2050, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 27, img: shoe, title: "Loafers Model 27", price: 2100, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 28, img: shoe, title: "Loafers Model 28", price: 2150, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 29, img: shoe, title: "Loafers Model 29", price: 2200, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 30, img: shoe, title: "Loafers Model 30", price: 2250, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 31, img: shoe, title: "Loafers Model 31", price: 2300, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 32, img: shoe, title: "Loafers Model 32", price: 2350, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 33, img: shoe, title: "Loafers Model 33", price: 2400, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 34, img: shoe, title: "Loafers Model 34", price: 2450, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 35, img: shoe, title: "Loafers Model 35", price: 2500, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 36, img: shoe, title: "Loafers Model 36", price: 2550, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 37, img: shoe, title: "Loafers Model 37", price: 2600, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 38, img: shoe, title: "Loafers Model 38", price: 2650, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 39, img: shoe, title: "Loafers Model 39", price: 2700, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 40, img: shoe, title: "Loafers Model 40", price: 2750, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 41, img: shoe, title: "Loafers Model 41", price: 2800, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 42, img: shoe, title: "Loafers Model 42", price: 2850, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 43, img: shoe, title: "Loafers Model 43", price: 2900, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 44, img: shoe, title: "Loafers Model 44", price: 2950, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 45, img: shoe, title: "Loafers Model 45", price: 3000, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 46, img: shoe, title: "Loafers Model 46", price: 3050, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 47, img: shoe, title: "Loafers Model 47", price: 3100, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 48, img: shoe, title: "Loafers Model 48", price: 3150, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 49, img: shoe, title: "Loafers Model 49", price: 3200, description: "Elegant and comfortable loafers suitable for casual and office wear." },
         { id: 50, img: shoe, title: "Loafers Model 50", price: 3250, description: "Elegant and comfortable loafers suitable for casual and office wear." }
      ]
   },

   {
      Category: "Formals",
      Products: [
         { id: 1, img: shoe, title: "Formal Model 1", price: 1200, description: "Stylish formal shoes perfect for office and events." },
         { id: 2, img: shoe, title: "Formal Model 2", price: 1250, description: "Stylish formal shoes perfect for office and events." },
         { id: 3, img: shoe, title: "Formal Model 3", price: 1300, description: "Stylish formal shoes perfect for office and events." },
         { id: 4, img: shoe, title: "Formal Model 4", price: 1350, description: "Stylish formal shoes perfect for office and events." },
         { id: 5, img: shoe, title: "Formal Model 5", price: 1400, description: "Stylish formal shoes perfect for office and events." },
         { id: 6, img: shoe, title: "Formal Model 6", price: 1450, description: "Stylish formal shoes perfect for office and events." },
         { id: 7, img: shoe, title: "Formal Model 7", price: 1500, description: "Stylish formal shoes perfect for office and events." },
         { id: 8, img: shoe, title: "Formal Model 8", price: 1550, description: "Stylish formal shoes perfect for office and events." },
         { id: 9, img: shoe, title: "Formal Model 9", price: 1600, description: "Stylish formal shoes perfect for office and events." },
         { id: 10, img: shoe, title: "Formal Model 10", price: 1650, description: "Stylish formal shoes perfect for office and events." },
         { id: 11, img: shoe, title: "Formal Model 11", price: 1700, description: "Stylish formal shoes perfect for office and events." },
         { id: 12, img: shoe, title: "Formal Model 12", price: 1750, description: "Stylish formal shoes perfect for office and events." },
         { id: 13, img: shoe, title: "Formal Model 13", price: 1800, description: "Stylish formal shoes perfect for office and events." },
         { id: 14, img: shoe, title: "Formal Model 14", price: 1850, description: "Stylish formal shoes perfect for office and events." },
         { id: 15, img: shoe, title: "Formal Model 15", price: 1900, description: "Stylish formal shoes perfect for office and events." },
         { id: 16, img: shoe, title: "Formal Model 16", price: 1950, description: "Stylish formal shoes perfect for office and events." },
         { id: 17, img: shoe, title: "Formal Model 17", price: 2000, description: "Stylish formal shoes perfect for office and events." },
         { id: 18, img: shoe, title: "Formal Model 18", price: 2050, description: "Stylish formal shoes perfect for office and events." },
         { id: 19, img: shoe, title: "Formal Model 19", price: 2100, description: "Stylish formal shoes perfect for office and events." },
         { id: 20, img: shoe, title: "Formal Model 20", price: 2150, description: "Stylish formal shoes perfect for office and events." },
         { id: 21, img: shoe, title: "Formal Model 21", price: 2200, description: "Stylish formal shoes perfect for office and events." },
         { id: 22, img: shoe, title: "Formal Model 22", price: 2250, description: "Stylish formal shoes perfect for office and events." },
         { id: 23, img: shoe, title: "Formal Model 23", price: 2300, description: "Stylish formal shoes perfect for office and events." },
         { id: 24, img: shoe, title: "Formal Model 24", price: 2350, description: "Stylish formal shoes perfect for office and events." },
         { id: 25, img: shoe, title: "Formal Model 25", price: 2400, description: "Stylish formal shoes perfect for office and events." },
         { id: 26, img: shoe, title: "Formal Model 26", price: 2450, description: "Stylish formal shoes perfect for office and events." },
         { id: 27, img: shoe, title: "Formal Model 27", price: 2500, description: "Stylish formal shoes perfect for office and events." },
         { id: 28, img: shoe, title: "Formal Model 28", price: 2550, description: "Stylish formal shoes perfect for office and events." },
         { id: 29, img: shoe, title: "Formal Model 29", price: 2600, description: "Stylish formal shoes perfect for office and events." },
         { id: 30, img: shoe, title: "Formal Model 30", price: 2650, description: "Stylish formal shoes perfect for office and events." },
         { id: 31, img: shoe, title: "Formal Model 31", price: 2700, description: "Stylish formal shoes perfect for office and events." },
         { id: 32, img: shoe, title: "Formal Model 32", price: 2750, description: "Stylish formal shoes perfect for office and events." },
         { id: 33, img: shoe, title: "Formal Model 33", price: 2800, description: "Stylish formal shoes perfect for office and events." },
         { id: 34, img: shoe, title: "Formal Model 34", price: 2850, description: "Stylish formal shoes perfect for office and events." },
         { id: 35, img: shoe, title: "Formal Model 35", price: 2900, description: "Stylish formal shoes perfect for office and events." },
         { id: 36, img: shoe, title: "Formal Model 36", price: 2950, description: "Stylish formal shoes perfect for office and events." },
         { id: 37, img: shoe, title: "Formal Model 37", price: 3000, description: "Stylish formal shoes perfect for office and events." },
         { id: 38, img: shoe, title: "Formal Model 38", price: 3050, description: "Stylish formal shoes perfect for office and events." },
         { id: 39, img: shoe, title: "Formal Model 39", price: 3100, description: "Stylish formal shoes perfect for office and events." },
         { id: 40, img: shoe, title: "Formal Model 40", price: 3150, description: "Stylish formal shoes perfect for office and events." },
         { id: 41, img: shoe, title: "Formal Model 41", price: 3200, description: "Stylish formal shoes perfect for office and events." },
         { id: 42, img: shoe, title: "Formal Model 42", price: 3250, description: "Stylish formal shoes perfect for office and events." },
         { id: 43, img: shoe, title: "Formal Model 43", price: 3300, description: "Stylish formal shoes perfect for office and events." },
         { id: 44, img: shoe, title: "Formal Model 44", price: 3350, description: "Stylish formal shoes perfect for office and events." },
         { id: 45, img: shoe, title: "Formal Model 45", price: 3400, description: "Stylish formal shoes perfect for office and events." },
         { id: 46, img: shoe, title: "Formal Model 46", price: 3450, description: "Stylish formal shoes perfect for office and events." },
         { id: 47, img: shoe, title: "Formal Model 47", price: 3500, description: "Stylish formal shoes perfect for office and events." },
         { id: 48, img: shoe, title: "Formal Model 48", price: 3550, description: "Stylish formal shoes perfect for office and events." },
         { id: 49, img: shoe, title: "Formal Model 49", price: 3600, description: "Stylish formal shoes perfect for office and events." },
         { id: 50, img: shoe, title: "Formal Model 50", price: 3650, description: "Stylish formal shoes perfect for office and events." }
      ]
   },


   {
      Category: "Sports",
      Products: [
         { id: 1, img: shoe, title: "Sports Model 1", price: 900, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 2, img: shoe, title: "Sports Model 2", price: 950, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 3, img: shoe, title: "Sports Model 3", price: 1000, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 4, img: shoe, title: "Sports Model 4", price: 1050, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 5, img: shoe, title: "Sports Model 5", price: 1100, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 6, img: shoe, title: "Sports Model 6", price: 1150, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 7, img: shoe, title: "Sports Model 7", price: 1200, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 8, img: shoe, title: "Sports Model 8", price: 1250, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 9, img: shoe, title: "Sports Model 9", price: 1300, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 10, img: shoe, title: "Sports Model 10", price: 1350, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 11, img: shoe, title: "Sports Model 11", price: 1400, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 12, img: shoe, title: "Sports Model 12", price: 1450, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 13, img: shoe, title: "Sports Model 13", price: 1500, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 14, img: shoe, title: "Sports Model 14", price: 1550, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 15, img: shoe, title: "Sports Model 15", price: 1600, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 16, img: shoe, title: "Sports Model 16", price: 1650, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 17, img: shoe, title: "Sports Model 17", price: 1700, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 18, img: shoe, title: "Sports Model 18", price: 1750, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 19, img: shoe, title: "Sports Model 19", price: 1800, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 20, img: shoe, title: "Sports Model 20", price: 1850, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 21, img: shoe, title: "Sports Model 21", price: 1900, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 22, img: shoe, title: "Sports Model 22", price: 1950, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 23, img: shoe, title: "Sports Model 23", price: 2000, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 24, img: shoe, title: "Sports Model 24", price: 2050, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 25, img: shoe, title: "Sports Model 25", price: 2100, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 26, img: shoe, title: "Sports Model 26", price: 2150, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 27, img: shoe, title: "Sports Model 27", price: 2200, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 28, img: shoe, title: "Sports Model 28", price: 2250, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 29, img: shoe, title: "Sports Model 29", price: 2300, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 30, img: shoe, title: "Sports Model 30", price: 2350, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 31, img: shoe, title: "Sports Model 31", price: 2400, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 32, img: shoe, title: "Sports Model 32", price: 2450, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 33, img: shoe, title: "Sports Model 33", price: 2500, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 34, img: shoe, title: "Sports Model 34", price: 2550, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 35, img: shoe, title: "Sports Model 35", price: 2600, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 36, img: shoe, title: "Sports Model 36", price: 2650, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 37, img: shoe, title: "Sports Model 37", price: 2700, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 38, img: shoe, title: "Sports Model 38", price: 2750, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 39, img: shoe, title: "Sports Model 39", price: 2800, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 40, img: shoe, title: "Sports Model 40", price: 2850, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 41, img: shoe, title: "Sports Model 41", price: 2900, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 42, img: shoe, title: "Sports Model 42", price: 2950, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 43, img: shoe, title: "Sports Model 43", price: 3000, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 44, img: shoe, title: "Sports Model 44", price: 3050, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 45, img: shoe, title: "Sports Model 45", price: 3100, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 46, img: shoe, title: "Sports Model 46", price: 3150, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 47, img: shoe, title: "Sports Model 47", price: 3200, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 48, img: shoe, title: "Sports Model 48", price: 3250, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 49, img: shoe, title: "Sports Model 49", price: 3300, description: "High-performance sports shoes for training and outdoor activities." },
         { id: 50, img: shoe, title: "Sports Model 50", price: 3350, description: "High-performance sports shoes for training and outdoor activities." }
      ]
   },


   {
      Category: "Casuals",
      Products: [
         { id: 1, img: shoe, title: "Casual Model 1", price: 700, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 2, img: shoe, title: "Casual Model 2", price: 750, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 3, img: shoe, title: "Casual Model 3", price: 800, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 4, img: shoe, title: "Casual Model 4", price: 850, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 5, img: shoe, title: "Casual Model 5", price: 900, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 6, img: shoe, title: "Casual Model 6", price: 950, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 7, img: shoe, title: "Casual Model 7", price: 1000, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 8, img: shoe, title: "Casual Model 8", price: 1050, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 9, img: shoe, title: "Casual Model 9", price: 1100, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 10, img: shoe, title: "Casual Model 10", price: 1150, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 11, img: shoe, title: "Casual Model 11", price: 1200, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 12, img: shoe, title: "Casual Model 12", price: 1250, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 13, img: shoe, title: "Casual Model 13", price: 1300, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 14, img: shoe, title: "Casual Model 14", price: 1350, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 15, img: shoe, title: "Casual Model 15", price: 1400, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 16, img: shoe, title: "Casual Model 16", price: 1450, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 17, img: shoe, title: "Casual Model 17", price: 1500, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 18, img: shoe, title: "Casual Model 18", price: 1550, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 19, img: shoe, title: "Casual Model 19", price: 1600, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 20, img: shoe, title: "Casual Model 20", price: 1650, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 21, img: shoe, title: "Casual Model 21", price: 1700, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 22, img: shoe, title: "Casual Model 22", price: 1750, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 23, img: shoe, title: "Casual Model 23", price: 1800, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 24, img: shoe, title: "Casual Model 24", price: 1850, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 25, img: shoe, title: "Casual Model 25", price: 1900, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 26, img: shoe, title: "Casual Model 26", price: 1950, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 27, img: shoe, title: "Casual Model 27", price: 2000, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 28, img: shoe, title: "Casual Model 28", price: 2050, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 29, img: shoe, title: "Casual Model 29", price: 2100, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 30, img: shoe, title: "Casual Model 30", price: 2150, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 31, img: shoe, title: "Casual Model 31", price: 2200, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 32, img: shoe, title: "Casual Model 32", price: 2250, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 33, img: shoe, title: "Casual Model 33", price: 2300, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 34, img: shoe, title: "Casual Model 34", price: 2350, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 35, img: shoe, title: "Casual Model 35", price: 2400, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 36, img: shoe, title: "Casual Model 36", price: 2450, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 37, img: shoe, title: "Casual Model 37", price: 2500, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 38, img: shoe, title: "Casual Model 38", price: 2550, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 39, img: shoe, title: "Casual Model 39", price: 2600, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 40, img: shoe, title: "Casual Model 40", price: 2650, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 41, img: shoe, title: "Casual Model 41", price: 2700, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 42, img: shoe, title: "Casual Model 42", price: 2750, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 43, img: shoe, title: "Casual Model 43", price: 2800, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 44, img: shoe, title: "Casual Model 44", price: 2850, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 45, img: shoe, title: "Casual Model 45", price: 2900, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 46, img: shoe, title: "Casual Model 46", price: 2950, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 47, img: shoe, title: "Casual Model 47", price: 3000, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 48, img: shoe, title: "Casual Model 48", price: 3050, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 49, img: shoe, title: "Casual Model 49", price: 3100, description: "Trendy casual shoes for everyday comfort and style." },
         { id: 50, img: shoe, title: "Casual Model 50", price: 3150, description: "Trendy casual shoes for everyday comfort and style." }
      ]
   }
];

export default suggestedData;